### PR TITLE
Change project home to Github

### PR DESCRIPTION
**Pull request by adamchainz**
By having the Github repo as the de-facto home you'll get more community participation :)

### CODE REVIEW

**Comment by adamchainz** [comment]
N.B. I also fixed some flake8 errors my editor showed in setup.py, mostly mixed tabs + spaces for indentation, which can look funky if users have tabs set to more or less than 4 spaces.

**Comment by avian2** [comment]
I've merged your `setup.py` whitespace fixes. Thanks.

**Comment by adamchainz** [comment]
Why not change the url to github?

**Comment by avian2** [comment]
I prefer to get feedback regarding Unidecode through email. Regardless, I added a link to GitHub to the README. Hence, I'm closing this pull request.

**Pull request closed without merging**
